CREATE TABLE FB ( date VARCHAR (20), value FLOAT, PRIMARY KEY (date));
CREATE TABLE YELP ( date VARCHAR (20), value FLOAT, PRIMARY KEY (date));
CREATE TABLE TWTR ( date VARCHAR (20), value FLOAT, PRIMARY KEY (date));
CREATE TABLE GRPN ( date VARCHAR (20), value FLOAT, PRIMARY KEY (date));
CREATE TABLE EBAY ( date VARCHAR (20), value FLOAT, PRIMARY KEY (date));
